// OpenVA - Open software platform for visual analytics
//
// Copyright (c) 2018, VTT Technical Research Centre of Finland Ltd
// All rights reserved.
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
//    1) Redistributions of source code must retain the above copyright
//       notice, this list of conditions and the following disclaimer.
//    2) Redistributions in binary form must reproduce the above copyright
//       notice, this list of conditions and the following disclaimer in the
//       documentation and/or other materials provided with the distribution.
//    3) Neither the name of the VTT Technical Research Centre of Finland nor the
//       names of its contributors may be used to endorse or promote products
//       derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS ``AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS AND CONTRIBUTORS BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
// (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
// ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

package fi.vtt.openva.domain;
// Generated Apr 11, 2017 9:44:02 AM by Hibernate Tools 5.2.0.Beta1

import java.time.LocalDateTime;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

// TODO: Auto-generated Javadoc
/**
 * Application generated by hbm2java.
 */
@Entity
@Table(name = "application", schema = "public")
public class Application implements java.io.Serializable {

	/** The id. */
	private int id;
	
	/** The title. */
	private String title;
	
	/** The description. */
	private String description;
	
	/** The time created. */
	private LocalDateTime timeCreated;
	
	/** The time deleted. */
	private LocalDateTime timeDeleted;
	
	private LocalDateTime maxTime;
	
	private LocalDateTime minTime;

	/**
	 * Instantiates a new application.
	 */
	public Application() {
	}

	/**
	 * Instantiates a new application.
	 *
	 * @param id the id
	 */
	public Application(int id) {
		this.id = id;
	}

	/**
	 * Instantiates a new application.
	 *
	 * @param id the id
	 * @param title the title
	 * @param description the description
	 * @param timeCreated the time created
	 * @param timeDeleted the time deleted
	 */
	public Application(int id, String title, String description, LocalDateTime timeCreated, LocalDateTime timeDeleted,LocalDateTime maxTime,LocalDateTime minTime) {
		this.id = id;
		this.title = title;
		this.description = description;
		this.timeCreated = timeCreated;
		this.timeDeleted = timeDeleted;
		this.maxTime = maxTime;
		this.minTime = minTime;
	}

	/**
	 * Gets the id.
	 *
	 * @return the id
	 */
	@Id
@GeneratedValue(strategy=GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	/**
	 * Sets the id.
	 *
	 * @param id the new id
	 */
	public void setId(int id) {
		this.id = id;
	}

	/**
	 * Gets the title.
	 *
	 * @return the title
	 */
	@Column(name = "title")
	public String getTitle() {
		return this.title;
	}

	/**
	 * Sets the title.
	 *
	 * @param title the new title
	 */
	public void setTitle(String title) {
		this.title = title;
	}
	
	/**
	 * Gets the description.
	 *
	 * @return the description
	 */
	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	/**
	 * Sets the description.
	 *
	 * @param description the new description
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * Gets the time created.
	 *
	 * @return the time created
	 */
	@Column(name = "time_created", length = 29)
	public LocalDateTime getTimeCreated() {
		return this.timeCreated;
	}

	/**
	 * Sets the time created.
	 *
	 * @param timeCreated the new time created
	 */
	public void setTimeCreated(LocalDateTime timeCreated) {
		this.timeCreated = timeCreated;
	}

	/**
	 * Gets the time deleted.
	 *
	 * @return the time deleted
	 */
	@Column(name = "time_deleted", length = 29)
	public LocalDateTime getTimeDeleted() {
		return this.timeDeleted;
	}

	/**
	 * Sets the time deleted.
	 *
	 * @param timeDeleted the new time deleted
	 */
	public void setTimeDeleted(LocalDateTime timeDeleted) {
		this.timeDeleted = timeDeleted;
	}

	
	/**
	 * Gets the max time.
	 *
	 * @return the max time
	 */
	@Column(name = "max_time", length = 29)
	public LocalDateTime getMaxTime() {
		return this.maxTime;
	}

	/**
	 * Sets the max time .
	 *
	 * @param maxTime the new max time
	 */
	public void setMaxTime(LocalDateTime maxTime) {
		this.maxTime = maxTime;
	}
	
	/**
	 * Gets the min time.
	 *
	 * @return the min time
	 */
	@Column(name = "min_time", length = 29)
	public LocalDateTime getMinTime() {
		return this.minTime;
	}

	/**
	 * Sets the min time
	 *
	 * @param minTime the new min time
	 */
	public void setMinTime(LocalDateTime minTime) {
		this.minTime = minTime;
	}
	
}
