// OpenVA - Open software platform for visual analytics
//
// Copyright (c) 2018, VTT Technical Research Centre of Finland Ltd
// All rights reserved.
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
//    1) Redistributions of source code must retain the above copyright
//       notice, this list of conditions and the following disclaimer.
//    2) Redistributions in binary form must reproduce the above copyright
//       notice, this list of conditions and the following disclaimer in the
//       documentation and/or other materials provided with the distribution.
//    3) Neither the name of the VTT Technical Research Centre of Finland nor the
//       names of its contributors may be used to endorse or promote products
//       derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS ``AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS AND CONTRIBUTORS BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
// (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
// ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

package fi.vtt.openva.domain;
// Generated Dec 1, 2016 10:45:58 AM by Hibernate Tools 5.1.0.Alpha1

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;



// TODO: Auto-generated Javadoc
/**
 * Codevalues generated by hbm2java.
 */
@Entity
@Table(name = "codevalues", schema = "public")
public class Codevalues implements java.io.Serializable {

	/** The id. */
	private int id;
	
	/** The codes. */
	private Codes codes;
	
	/** The codes title. */
	private String codesTitle;
	
	/** The code value. */
	private String codeValue;
	
	/** The title. */
	private String title;
	
	/** The time created. */
	private LocalDateTime timeCreated;
	
	/** The time deleted. */
	private LocalDateTime timeDeleted;

	/**
	 * Instantiates a new codevalues.
	 */
	public Codevalues() {
	}

	/**
	 * Instantiates a new codevalues.
	 *
	 * @param id the id
	 */
	public Codevalues(int id) {
		this.id = id;
	}

	/**
	 * Instantiates a new codevalues.
	 *
	 * @param id the id
	 * @param codes the codes
	 * @param codesTitle the codes title
	 * @param codeValue the code value
	 * @param title the title
	 * @param timeCreated the time created
	 * @param timeDeleted the time deleted
	 */
	public Codevalues(int id, Codes codes, String codesTitle, String codeValue, String title, LocalDateTime timeCreated,
			LocalDateTime timeDeleted) {
		this.id = id;
		this.codes = codes;
		this.codesTitle = codesTitle;
		this.codeValue = codeValue;
		this.title = title;
		this.timeCreated = timeCreated;
		this.timeDeleted = timeDeleted;
	}

	/**
	 * Gets the id.
	 *
	 * @return the id
	 */
	@Id
@GeneratedValue(strategy=GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	/**
	 * Sets the id.
	 *
	 * @param id the new id
	 */
	public void setId(int id) {
		this.id = id;
	}

	/**
	 * Gets the codes.
	 *
	 * @return the codes
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codes_id")
	public Codes getCodes() {
		return this.codes;
	}

	/**
	 * Sets the codes.
	 *
	 * @param codes the new codes
	 */
	public void setCodes(Codes codes) {
		this.codes = codes;
	}

	/**
	 * Gets the codes title.
	 *
	 * @return the codes title
	 */
	@Column(name = "codes_title")
	public String getCodesTitle() {
		return this.codesTitle;
	}

	/**
	 * Sets the codes title.
	 *
	 * @param codesTitle the new codes title
	 */
	public void setCodesTitle(String codesTitle) {
		this.codesTitle = codesTitle;
	}

	/**
	 * Gets the code value.
	 *
	 * @return the code value
	 */
	@Column(name = "code_value")
	public String getCodeValue() {
		return this.codeValue;
	}

	/**
	 * Sets the code value.
	 *
	 * @param codeValue the new code value
	 */
	public void setCodeValue(String codeValue) {
		this.codeValue = codeValue;
	}

	/**
	 * Gets the title.
	 *
	 * @return the title
	 */
	@Column(name = "title")
	public String getTitle() {
		return this.title;
	}

	/**
	 * Sets the title.
	 *
	 * @param title the new title
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	
	/**
	 * Gets the time created.
	 *
	 * @return the time created
	 */
	@Column(name = "time_created", length = 29)
	public LocalDateTime getTimeCreated() {
		return this.timeCreated;
	}

	/**
	 * Sets the time created.
	 *
	 * @param timeCreated the new time created
	 */
	public void setTimeCreated(LocalDateTime timeCreated) {
		this.timeCreated = timeCreated;
	}

	
	/**
	 * Gets the time deleted.
	 *
	 * @return the time deleted
	 */
	@Column(name = "time_deleted", length = 29)
	public LocalDateTime getTimeDeleted() {
		return this.timeDeleted;
	}

	/**
	 * Sets the time deleted.
	 *
	 * @param timeDeleted the new time deleted
	 */
	public void setTimeDeleted(LocalDateTime timeDeleted) {
		this.timeDeleted = timeDeleted;
	}

}
