// OpenVA - Open software platform for visual analytics
//
// Copyright (c) 2018, VTT Technical Research Centre of Finland Ltd
// All rights reserved.
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
//    1) Redistributions of source code must retain the above copyright
//       notice, this list of conditions and the following disclaimer.
//    2) Redistributions in binary form must reproduce the above copyright
//       notice, this list of conditions and the following disclaimer in the
//       documentation and/or other materials provided with the distribution.
//    3) Neither the name of the VTT Technical Research Centre of Finland nor the
//       names of its contributors may be used to endorse or promote products
//       derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS ``AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS AND CONTRIBUTORS BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
// (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
// ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

package fi.vtt.openva.domain;
// Generated Dec 1, 2016 10:45:58 AM by Hibernate Tools 5.1.0.Alpha1

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;



// TODO: Auto-generated Javadoc
/**
 * Codes generated by hbm2java.
 */
@Entity
@Table(name = "codes", schema = "public")
public class Codes implements java.io.Serializable {

	/** The id. */
	private int id;
	
	/** The title. */
	private String title;
	
	/** The description. */
	private String description;
	
	/** The time created. */
	private LocalDateTime timeCreated;
	
	/** The time deleted. */
	private LocalDateTime timeDeleted;
	
	/** The oitype properties. */
	private Set<OitypeProperty> oitypeProperties = new HashSet<OitypeProperty>(0);
	
	/** The codevalueses. */
	private Set<Codevalues> codevalueses = new HashSet<Codevalues>(0);

	/**
	 * Instantiates a new codes.
	 */
	public Codes() {
	}

	/**
	 * Instantiates a new codes.
	 *
	 * @param id the id
	 */
	public Codes(int id) {
		this.id = id;
	}

	/**
	 * Instantiates a new codes.
	 *
	 * @param id the id
	 * @param title the title
	 * @param description the description
	 * @param timeCreated the time created
	 * @param timeDeleted the time deleted
	 * @param oitypeProperties the oitype properties
	 * @param codevalueses the codevalueses
	 */
	public Codes(int id, String title, String description, LocalDateTime timeCreated, LocalDateTime timeDeleted,
			Set<OitypeProperty> oitypeProperties, Set<Codevalues> codevalueses) {
		this.id = id;
		this.title = title;
		this.description = description;
		this.timeCreated = timeCreated;
		this.timeDeleted = timeDeleted;
		this.oitypeProperties = oitypeProperties;
		this.codevalueses = codevalueses;
	}

	/**
	 * Gets the id.
	 *
	 * @return the id
	 */
	@Id
@GeneratedValue(strategy=GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	/**
	 * Sets the id.
	 *
	 * @param id the new id
	 */
	public void setId(int id) {
		this.id = id;
	}

	/**
	 * Gets the title.
	 *
	 * @return the title
	 */
	@Column(name = "title")
	public String getTitle() {
		return this.title;
	}

	/**
	 * Sets the title.
	 *
	 * @param title the new title
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * Gets the description.
	 *
	 * @return the description
	 */
	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	/**
	 * Sets the description.
	 *
	 * @param description the new description
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	
	/**
	 * Gets the time created.
	 *
	 * @return the time created
	 */
	@Column(name = "time_created", length = 29)
	public LocalDateTime getTimeCreated() {
		return this.timeCreated;
	}

	/**
	 * Sets the time created.
	 *
	 * @param timeCreated the new time created
	 */
	public void setTimeCreated(LocalDateTime timeCreated) {
		this.timeCreated = timeCreated;
	}

	
	/**
	 * Gets the time deleted.
	 *
	 * @return the time deleted
	 */
	@Column(name = "time_deleted", length = 29)
	public LocalDateTime getTimeDeleted() {
		return this.timeDeleted;
	}

	/**
	 * Sets the time deleted.
	 *
	 * @param timeDeleted the new time deleted
	 */
	public void setTimeDeleted(LocalDateTime timeDeleted) {
		this.timeDeleted = timeDeleted;
	}

	/**
	 * Gets the oitype properties.
	 *
	 * @return the oitype properties
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "codes")
	public Set<OitypeProperty> getOitypeProperties() {
		return this.oitypeProperties;
	}

	/**
	 * Sets the oitype properties.
	 *
	 * @param oitypeProperties the new oitype properties
	 */
	public void setOitypeProperties(Set<OitypeProperty> oitypeProperties) {
		this.oitypeProperties = oitypeProperties;
	}

	/**
	 * Gets the codevalueses.
	 *
	 * @return the codevalueses
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "codes")
	public Set<Codevalues> getCodevalueses() {
		return this.codevalueses;
	}

	/**
	 * Sets the codevalueses.
	 *
	 * @param codevalueses the new codevalueses
	 */
	public void setCodevalueses(Set<Codevalues> codevalueses) {
		this.codevalueses = codevalueses;
	}

}
