// OpenVA - Open software platform for visual analytics
//
// Copyright (c) 2018, VTT Technical Research Centre of Finland Ltd
// All rights reserved.
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
//    1) Redistributions of source code must retain the above copyright
//       notice, this list of conditions and the following disclaimer.
//    2) Redistributions in binary form must reproduce the above copyright
//       notice, this list of conditions and the following disclaimer in the
//       documentation and/or other materials provided with the distribution.
//    3) Neither the name of the VTT Technical Research Centre of Finland nor the
//       names of its contributors may be used to endorse or promote products
//       derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS ``AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS AND CONTRIBUTORS BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
// (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
// ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

package fi.vtt.openva.domain;
// Generated Dec 1, 2016 10:45:58 AM by Hibernate Tools 5.1.0.Alpha1

import java.time.LocalDateTime;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;


/**
 * GroupMember generated by hbm2java.
 */
@Entity
@Table(name = "group_member", schema = "public")
public class GroupMember implements java.io.Serializable {

	/** The id. */
	private int id;
	
	/** The oitype property. */
	private OitypeProperty oitypeProperty;
	
	/** The property group. */
	private PropertyGroup propertyGroup;
	
	/** The oitype property title. */
	private String oitypePropertyTitle;
	
	/** The property group title. */
	private String propertyGroupTitle;
	
	/** The time created. */
	private LocalDateTime timeCreated;
	
	/** The time deleted. */
	private LocalDateTime timeDeleted;

	/**
	 * Instantiates a new group member.
	 */
	public GroupMember() {
	}

	/**
	 * Instantiates a new group member.
	 *
	 * @param id the id
	 */
	public GroupMember(int id) {
		this.id = id;
	}

	/**
	 * Instantiates a new group member.
	 *
	 * @param id the id
	 * @param oitypeProperty the oitype property
	 * @param propertyGroup the property group
	 * @param oitypePropertyTitle the oitype property title
	 * @param propertyGroupTitle the property group title
	 * @param timeCreated the time created
	 * @param timeDeleted the time deleted
	 */
	public GroupMember(int id, OitypeProperty oitypeProperty, PropertyGroup propertyGroup, String oitypePropertyTitle,
			String propertyGroupTitle, LocalDateTime timeCreated, LocalDateTime timeDeleted) {
		this.id = id;
		this.oitypeProperty = oitypeProperty;
		this.propertyGroup = propertyGroup;
		this.oitypePropertyTitle = oitypePropertyTitle;
		this.propertyGroupTitle = propertyGroupTitle;
		this.timeCreated = timeCreated;
		this.timeDeleted = timeDeleted;
	}

	/**
	 * Gets the id.
	 *
	 * @return the id
	 */
	@Id
@GeneratedValue(strategy=GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	/**
	 * Sets the id.
	 *
	 * @param id the new id
	 */
	public void setId(int id) {
		this.id = id;
	}

	/**
	 * Gets the oitype property.
	 *
	 * @return the oitype property
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "oitype_property_id")
	public OitypeProperty getOitypeProperty() {
		return this.oitypeProperty;
	}

	/**
	 * Sets the oitype property.
	 *
	 * @param oitypeProperty the new oitype property
	 */
	public void setOitypeProperty(OitypeProperty oitypeProperty) {
		this.oitypeProperty = oitypeProperty;
	}

	/**
	 * Gets the property group.
	 *
	 * @return the property group
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "property_group_id")
	public PropertyGroup getPropertyGroup() {
		return this.propertyGroup;
	}

	/**
	 * Sets the property group.
	 *
	 * @param propertyGroup the new property group
	 */
	public void setPropertyGroup(PropertyGroup propertyGroup) {
		this.propertyGroup = propertyGroup;
	}

	/**
	 * Gets the oitype property title.
	 *
	 * @return the oitype property title
	 */
	@Column(name = "oitype_property_title")
	public String getOitypePropertyTitle() {
		return this.oitypePropertyTitle;
	}

	/**
	 * Sets the oitype property title.
	 *
	 * @param oitypePropertyTitle the new oitype property title
	 */
	public void setOitypePropertyTitle(String oitypePropertyTitle) {
		this.oitypePropertyTitle = oitypePropertyTitle;
	}

	/**
	 * Gets the property group title.
	 *
	 * @return the property group title
	 */
	@Column(name = "property_group_title")
	public String getPropertyGroupTitle() {
		return this.propertyGroupTitle;
	}

	/**
	 * Sets the property group title.
	 *
	 * @param propertyGroupTitle the new property group title
	 */
	public void setPropertyGroupTitle(String propertyGroupTitle) {
		this.propertyGroupTitle = propertyGroupTitle;
	}

	
	/**
	 * Gets the time created.
	 *
	 * @return the time created
	 */
	@Column(name = "time_created", length = 29)
	public LocalDateTime getTimeCreated() {
		return this.timeCreated;
	}

	/**
	 * Sets the time created.
	 *
	 * @param timeCreated the new time created
	 */
	public void setTimeCreated(LocalDateTime timeCreated) {
		this.timeCreated = timeCreated;
	}

	
	/**
	 * Gets the time deleted.
	 *
	 * @return the time deleted
	 */
	@Column(name = "time_deleted", length = 29)
	public LocalDateTime getTimeDeleted() {
		return this.timeDeleted;
	}

	/**
	 * Sets the time deleted.
	 *
	 * @param timeDeleted the new time deleted
	 */
	public void setTimeDeleted(LocalDateTime timeDeleted) {
		this.timeDeleted = timeDeleted;
	}

}
