// OpenVA - Open software platform for visual analytics
//
// Copyright (c) 2018, VTT Technical Research Centre of Finland Ltd
// All rights reserved.
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
//    1) Redistributions of source code must retain the above copyright
//       notice, this list of conditions and the following disclaimer.
//    2) Redistributions in binary form must reproduce the above copyright
//       notice, this list of conditions and the following disclaimer in the
//       documentation and/or other materials provided with the distribution.
//    3) Neither the name of the VTT Technical Research Centre of Finland nor the
//       names of its contributors may be used to endorse or promote products
//       derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS ``AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS AND CONTRIBUTORS BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
// (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
// ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

package fi.vtt.openva.domain;
// Generated Dec 1, 2016 10:45:58 AM by Hibernate Tools 5.1.0.Alpha1

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;



// TODO: Auto-generated Javadoc
/**
 * OiBackgroundpropertyValue generated by hbm2java.
 */
@Entity
@Table(name = "oi_backgroundproperty_value", schema = "public")
public class OiBackgroundpropertyValue implements java.io.Serializable {

	/** The id. */
	private int id;
	
	/** The objectofinterest. */
	private Objectofinterest objectofinterest;
	
	/** The oitype property. */
	private OitypeProperty oitypeProperty;
	
	/** The oitype property title. */
	private String oitypePropertyTitle;
	
	/** The oi title. */
	private String oiTitle;
	
	/** The value. */
	private Float backgroundValue;
	
	/** The codevalue. */
	private String codeValue;
	
	/** The valid from. */
	private LocalDateTime validFrom;
	
	/** The valid to. */
	private LocalDateTime validTo;
	
	/** The time created. */
	private LocalDateTime timeCreated;
	
	/** The time deleted. */
	private LocalDateTime timeDeleted;
	
//	/** The title. */
//	private String title;

	/**
	 * Instantiates a new oi backgroundproperty value.
	 */
	public OiBackgroundpropertyValue() {
	}

	/**
	 * Instantiates a new oi backgroundproperty value.
	 *
	 * @param id the id
	 */
	public OiBackgroundpropertyValue(int id) {
		this.id = id;
	}


	public OiBackgroundpropertyValue(int id, Objectofinterest objectofinterest, OitypeProperty oitypeProperty,
			String oitypePropertyTitle, String oiTitle, Float value,String codeValue, LocalDateTime validFrom, LocalDateTime validTo, LocalDateTime timeCreated,
			LocalDateTime timeDeleted, String title) {
		this.id = id;
		this.objectofinterest = objectofinterest;
		this.oitypeProperty = oitypeProperty;
		this.oitypePropertyTitle = oitypePropertyTitle;
		this.oiTitle = oiTitle;
		this.backgroundValue = value;
		this.codeValue = codeValue;
		this.validFrom = validFrom;
		this.validTo = validTo;
		this.timeCreated = timeCreated;
		this.timeDeleted = timeDeleted;
//		this.title = title;
	}

	/**
	 * Gets the id.
	 *
	 * @return the id
	 */
	@Id
@GeneratedValue(strategy=GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	/**
	 * Sets the id.
	 *
	 * @param id the new id
	 */
	public void setId(int id) {
		this.id = id;
	}

	/**
	 * Gets the objectofinterest.
	 *
	 * @return the objectofinterest
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "oi_id")
	public Objectofinterest getObjectofinterest() {
		return this.objectofinterest;
	}

	/**
	 * Sets the objectofinterest.
	 *
	 * @param objectofinterest the new objectofinterest
	 */
	public void setObjectofinterest(Objectofinterest objectofinterest) {
		this.objectofinterest = objectofinterest;
	}

	/**
	 * Gets the oitype property.
	 *
	 * @return the oitype property
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "oitype_property_id")
	public OitypeProperty getOitypeProperty() {
		return this.oitypeProperty;
	}

	/**
	 * Sets the oitype property.
	 *
	 * @param oitypeProperty the new oitype property
	 */
	public void setOitypeProperty(OitypeProperty oitypeProperty) {
		this.oitypeProperty = oitypeProperty;
	}

	/**
	 * Gets the oitype property title.
	 *
	 * @return the oitype property title
	 */
	@Column(name = "oitype_property_title")
	public String getOitypePropertyTitle() {
		return this.oitypePropertyTitle;
	}

	/**
	 * Sets the oitype property title.
	 *
	 * @param oitypePropertyTitle the new oitype property title
	 */
	public void setOitypePropertyTitle(String oitypePropertyTitle) {
		this.oitypePropertyTitle = oitypePropertyTitle;
	}

	/**
	 * Gets the oi title.
	 *
	 * @return the oi title
	 */
	@Column(name = "oi_title")
	public String getOiTitle() {
		return this.oiTitle;
	}

	/**
	 * Sets the oi title.
	 *
	 * @param oiTitle the new oi title
	 */
	public void setOiTitle(String oiTitle) {
		this.oiTitle = oiTitle;
	}

	/**
	 * Gets the value.
	 *
	 * @return the value
	 */
	@Column(name = "background_value", precision = 8, scale = 8)
	public Float getValue() {
		return this.backgroundValue;
	}

	/**
	 * Sets the value.
	 *
	 * @param value the new value
	 */
	public void setValue(Float value) {
		this.backgroundValue = value;
	}

	@Column(name = "codevalue", precision = 8, scale = 8)
	public String getCodeValue() {
		return this.codeValue;
	}

	/**
	 * Sets the value.
	 *
	 * @param value the new value
	 */
	public void setCodeValue(String value) {
		this.codeValue = value;
	}

	
	
	/**
	 * Gets the valid from.
	 *
	 * @return the valid from
	 */
	@Column(name = "valid_from", length = 29)
	public LocalDateTime getValidFrom() {
		return this.validFrom;
	}

	/**
	 * Sets the valid from.
	 *
	 * @param validFrom the new valid from
	 */
	public void setValidFrom(LocalDateTime validFrom) {
		this.validFrom = validFrom;
	}

	
	/**
	 * Gets the valid to.
	 *
	 * @return the valid to
	 */
	@Column(name = "valid_to", length = 29)
	public LocalDateTime getValidTo() {
		return this.validTo;
	}

	/**
	 * Sets the valid to.
	 *
	 * @param validTo the new valid to
	 */
	public void setValidTo(LocalDateTime validTo) {
		this.validTo = validTo;
	}

	
	/**
	 * Gets the time created.
	 *
	 * @return the time created
	 */
	@Column(name = "time_created", length = 29)
	public LocalDateTime getTimeCreated() {
		return this.timeCreated;
	}

	/**
	 * Sets the time created.
	 *
	 * @param timeCreated the new time created
	 */
	public void setTimeCreated(LocalDateTime timeCreated) {
		this.timeCreated = timeCreated;
	}

	
	/**
	 * Gets the time deleted.
	 *
	 * @return the time deleted
	 */
	@Column(name = "time_deleted", length = 29)
	public LocalDateTime getTimeDeleted() {
		return this.timeDeleted;
	}

	/**
	 * Sets the time deleted.
	 *
	 * @param timeDeleted the new time deleted
	 */
	public void setTimeDeleted(LocalDateTime timeDeleted) {
		this.timeDeleted = timeDeleted;
	}

//	/**
//	 * Gets the title.
//	 *
//	 * @return the title
//	 */
//	@Column(name = "title")
//	public String getTitle() {
//		return this.title;
//	}
//
//	/**
//	 * Sets the title.
//	 *
//	 * @param title the new title
//	 */
//	public void setTitle(String title) {
//		this.title = title;
//	}

}
