// OpenVA - Open software platform for visual analytics
//
// Copyright (c) 2018, VTT Technical Research Centre of Finland Ltd
// All rights reserved.
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
//    1) Redistributions of source code must retain the above copyright
//       notice, this list of conditions and the following disclaimer.
//    2) Redistributions in binary form must reproduce the above copyright
//       notice, this list of conditions and the following disclaimer in the
//       documentation and/or other materials provided with the distribution.
//    3) Neither the name of the VTT Technical Research Centre of Finland nor the
//       names of its contributors may be used to endorse or promote products
//       derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS ``AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS AND CONTRIBUTORS BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
// (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
// ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

package fi.vtt.openva.domain;

import org.hibernate.annotations.Type;
// Generated Oct 13, 2016 4:34:05 PM by Hibernate Tools 5.1.0.Alpha1

import fi.vtt.openva.dao.PropertyEnum;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

// TODO: Auto-generated Javadoc
/**
 * OitypeIndex generated by hbm2java.
 */
@Entity
@Table(name = "oitype_index", schema = "public")
public class OitypeIndex implements java.io.Serializable {

	/** The id. */
	private int id;
	
	/** The codes. */
	private Codes codes;
	
	/** The oitype. */
	private Oitype oitype;
	
	/** The oitype title. */
	private String oitypeTitle;
	
	/** The title. */
	private String title;
	
	/** The report title. */
	private String reportTitle;
	
	/** The description. */
	private String description;
	
	/** The variabletype. */
	private String variabletype;
	
	/** The propertytype. */
	private PropertyEnum propertytype;
	
	/** The datatype. */
	private String datatype;
	
	/** The numunit. */
	private String numunit;
	
	/** The codes title. */
	private String codesTitle;
	
	/** The lowerlimit. */
	private Float lowerlimit;
	
	/** The upperlimit. */
	private Float upperlimit;
	
	/** The goalvalue. */
	private Float goalvalue;
	
	/** The referencevalue. */
	private Float referencevalue;
	
	/** The measurementtype. */
	private String measurementtype;
	
	/** The frequency. */
	private String frequency;
	
	/** The time created. */
	private Date timeCreated;
	
	/** The time deleted. */
	private Date timeDeleted;
	
	/** The oi index values. */
	private Set<OiIndexValue> oiIndexValues = new HashSet<OiIndexValue>(0);

	/**
	 * Instantiates a new oitype index.
	 */
	public OitypeIndex() {
	}

	/**
	 * Instantiates a new oitype index.
	 *
	 * @param id the id
	 */
	public OitypeIndex(int id) {
		this.id = id;
	}

	/**
	 * Instantiates a new oitype index.
	 *
	 * @param id the id
	 * @param codes the codes
	 * @param oitype the oitype
	 * @param oitypeTitle the oitype title
	 * @param title the title
	 * @param reportTitle the report title
	 * @param description the description
	 * @param variabletype the variabletype
	 * @param propertytype the propertytype
	 * @param datatype the datatype
	 * @param numunit the numunit
	 * @param codesTitle the codes title
	 * @param lowerlimit the lowerlimit
	 * @param upperlimit the upperlimit
	 * @param goalvalue the goalvalue
	 * @param referencevalue the referencevalue
	 * @param measurementtype the measurementtype
	 * @param frequency the frequency
	 * @param timeCreated the time created
	 * @param timeDeleted the time deleted
	 * @param oiIndexValues the oi index values
	 */
	public OitypeIndex(int id, Codes codes, Oitype oitype, String oitypeTitle, String title, String reportTitle,
			String description, String variabletype, PropertyEnum propertytype, String datatype, String numunit,
			String codesTitle, Float lowerlimit, Float upperlimit, Float goalvalue, Float referencevalue,
			String measurementtype, String frequency, Date timeCreated, Date timeDeleted,
			Set<OiIndexValue> oiIndexValues) {
		this.id = id;
		this.codes = codes;
		this.oitype = oitype;
		this.oitypeTitle = oitypeTitle;
		this.title = title;
		this.reportTitle = reportTitle;
		this.description = description;
		this.variabletype = variabletype;
		this.propertytype = propertytype;
		this.datatype = datatype;
		this.numunit = numunit;
		this.codesTitle = codesTitle;
		this.lowerlimit = lowerlimit;
		this.upperlimit = upperlimit;
		this.goalvalue = goalvalue;
		this.referencevalue = referencevalue;
		this.measurementtype = measurementtype;
		this.frequency = frequency;
		this.timeCreated = timeCreated;
		this.timeDeleted = timeDeleted;
		this.oiIndexValues = oiIndexValues;
	}

	/**
	 * Gets the id.
	 *
	 * @return the id
	 */
	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	/**
	 * Sets the id.
	 *
	 * @param id the new id
	 */
	public void setId(int id) {
		this.id = id;
	}

	/**
	 * Gets the codes.
	 *
	 * @return the codes
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codes_id")
	public Codes getCodes() {
		return this.codes;
	}

	/**
	 * Sets the codes.
	 *
	 * @param codes the new codes
	 */
	public void setCodes(Codes codes) {
		this.codes = codes;
	}

	/**
	 * Gets the oitype.
	 *
	 * @return the oitype
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "oitype_id")
	public Oitype getOitype() {
		return this.oitype;
	}

	/**
	 * Sets the oitype.
	 *
	 * @param oitype the new oitype
	 */
	public void setOitype(Oitype oitype) {
		this.oitype = oitype;
	}

	/**
	 * Gets the oitype title.
	 *
	 * @return the oitype title
	 */
	@Column(name = "oitype_title")
	public String getOitypeTitle() {
		return this.oitypeTitle;
	}

	/**
	 * Sets the oitype title.
	 *
	 * @param oitypeTitle the new oitype title
	 */
	public void setOitypeTitle(String oitypeTitle) {
		this.oitypeTitle = oitypeTitle;
	}

	/**
	 * Gets the title.
	 *
	 * @return the title
	 */
	@Column(name = "title")
	public String getTitle() {
		return this.title;
	}

	/**
	 * Sets the title.
	 *
	 * @param title the new title
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * Gets the report title.
	 *
	 * @return the report title
	 */
	@Column(name = "report_title")
	public String getReportTitle() {
		return this.reportTitle;
	}

	/**
	 * Sets the report title.
	 *
	 * @param reportTitle the new report title
	 */
	public void setReportTitle(String reportTitle) {
		this.reportTitle = reportTitle;
	}

	/**
	 * Gets the description.
	 *
	 * @return the description
	 */
	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	/**
	 * Sets the description.
	 *
	 * @param description the new description
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * Gets the variabletype.
	 *
	 * @return the variabletype
	 */
	@Column(name = "variabletype")
	public String getVariabletype() {
		return this.variabletype;
	}

	/**
	 * Sets the variabletype.
	 *
	 * @param variabletype the new variabletype
	 */
	public void setVariabletype(String variabletype) {
		this.variabletype = variabletype;
	}

	/**
	 * Gets the propertytype.
	 *
	 * @return the propertytype
	 */
	@Column(name = "propertytype")
	@Type(type="fi.vtt.openva.dao.PropertyEnumType")
public PropertyEnum getPropertytype() {
		return this.propertytype;
	}

	/**
	 * Sets the propertytype.
	 *
	 * @param propertytype the new propertytype
	 */
	public void setPropertytype(PropertyEnum propertytype) {
		this.propertytype = propertytype;
	}

	/**
	 * Gets the datatype.
	 *
	 * @return the datatype
	 */
	@Column(name = "datatype")
	public String getDatatype() {
		return this.datatype;
	}

	/**
	 * Sets the datatype.
	 *
	 * @param datatype the new datatype
	 */
	public void setDatatype(String datatype) {
		this.datatype = datatype;
	}

	/**
	 * Gets the numunit.
	 *
	 * @return the numunit
	 */
	@Column(name = "numunit")
	public String getNumunit() {
		return this.numunit;
	}

	/**
	 * Sets the numunit.
	 *
	 * @param numunit the new numunit
	 */
	public void setNumunit(String numunit) {
		this.numunit = numunit;
	}

	/**
	 * Gets the codes title.
	 *
	 * @return the codes title
	 */
	@Column(name = "codes_title")
	public String getCodesTitle() {
		return this.codesTitle;
	}

	/**
	 * Sets the codes title.
	 *
	 * @param codesTitle the new codes title
	 */
	public void setCodesTitle(String codesTitle) {
		this.codesTitle = codesTitle;
	}

	/**
	 * Gets the lowerlimit.
	 *
	 * @return the lowerlimit
	 */
	@Column(name = "lowerlimit", precision = 8, scale = 8)
	public Float getLowerlimit() {
		return this.lowerlimit;
	}

	/**
	 * Sets the lowerlimit.
	 *
	 * @param lowerlimit the new lowerlimit
	 */
	public void setLowerlimit(Float lowerlimit) {
		this.lowerlimit = lowerlimit;
	}

	/**
	 * Gets the upperlimit.
	 *
	 * @return the upperlimit
	 */
	@Column(name = "upperlimit", precision = 8, scale = 8)
	public Float getUpperlimit() {
		return this.upperlimit;
	}

	/**
	 * Sets the upperlimit.
	 *
	 * @param upperlimit the new upperlimit
	 */
	public void setUpperlimit(Float upperlimit) {
		this.upperlimit = upperlimit;
	}

	/**
	 * Gets the goalvalue.
	 *
	 * @return the goalvalue
	 */
	@Column(name = "goalvalue", precision = 8, scale = 8)
	public Float getGoalvalue() {
		return this.goalvalue;
	}

	/**
	 * Sets the goalvalue.
	 *
	 * @param goalvalue the new goalvalue
	 */
	public void setGoalvalue(Float goalvalue) {
		this.goalvalue = goalvalue;
	}

	/**
	 * Gets the referencevalue.
	 *
	 * @return the referencevalue
	 */
	@Column(name = "referencevalue", precision = 8, scale = 8)
	public Float getReferencevalue() {
		return this.referencevalue;
	}

	/**
	 * Sets the referencevalue.
	 *
	 * @param referencevalue the new referencevalue
	 */
	public void setReferencevalue(Float referencevalue) {
		this.referencevalue = referencevalue;
	}

	/**
	 * Gets the measurementtype.
	 *
	 * @return the measurementtype
	 */
	@Column(name = "measurementtype")
	public String getMeasurementtype() {
		return this.measurementtype;
	}

	/**
	 * Sets the measurementtype.
	 *
	 * @param measurementtype the new measurementtype
	 */
	public void setMeasurementtype(String measurementtype) {
		this.measurementtype = measurementtype;
	}

	/**
	 * Gets the frequency.
	 *
	 * @return the frequency
	 */
	@Column(name = "frequency")
	public String getFrequency() {
		return this.frequency;
	}

	/**
	 * Sets the frequency.
	 *
	 * @param frequency the new frequency
	 */
	public void setFrequency(String frequency) {
		this.frequency = frequency;
	}

	/**
	 * Gets the time created.
	 *
	 * @return the time created
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_created", length = 29)
	public Date getTimeCreated() {
		return this.timeCreated;
	}

	/**
	 * Sets the time created.
	 *
	 * @param timeCreated the new time created
	 */
	public void setTimeCreated(Date timeCreated) {
		this.timeCreated = timeCreated;
	}

	/**
	 * Gets the time deleted.
	 *
	 * @return the time deleted
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_deleted", length = 29)
	public Date getTimeDeleted() {
		return this.timeDeleted;
	}

	/**
	 * Sets the time deleted.
	 *
	 * @param timeDeleted the new time deleted
	 */
	public void setTimeDeleted(Date timeDeleted) {
		this.timeDeleted = timeDeleted;
	}

	/**
	 * Gets the oi index values.
	 *
	 * @return the oi index values
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "oitypeIndex")
	public Set<OiIndexValue> getOiIndexValues() {
		return this.oiIndexValues;
	}

	/**
	 * Sets the oi index values.
	 *
	 * @param oiIndexValues the new oi index values
	 */
	public void setOiIndexValues(Set<OiIndexValue> oiIndexValues) {
		this.oiIndexValues = oiIndexValues;
	}

}
