// OpenVA - Open software platform for visual analytics
//
// Copyright (c) 2018, VTT Technical Research Centre of Finland Ltd
// All rights reserved.
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
//    1) Redistributions of source code must retain the above copyright
//       notice, this list of conditions and the following disclaimer.
//    2) Redistributions in binary form must reproduce the above copyright
//       notice, this list of conditions and the following disclaimer in the
//       documentation and/or other materials provided with the distribution.
//    3) Neither the name of the VTT Technical Research Centre of Finland nor the
//       names of its contributors may be used to endorse or promote products
//       derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS ``AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS AND CONTRIBUTORS BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
// (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
// ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

package fi.vtt.openva.domain;


import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Type;
import fi.vtt.openva.dao.PropertyEnum;

/**
 * OitypeProperty generated by hbm2java
 */
@Entity
@Table(name = "oitype_property", schema = "public")
public class OitypeProperty implements java.io.Serializable {

	private int id;
	private Codes codes;
	private Oitype oitype;
	private String oitypeTitle;
	private String title;
	private String reportTitle;
	private String sourceTitle;
	private String description;
	private String dataSource;
	private String variabletype;
	private String propertytype;
	private String datatype;
	private String quanttype;
	private String numunit;
	private String codesTitle;
	private Float lowerlimit;
	private Float upperlimit;
	private Float alarmLowerlimit;
	private Float alarmUpperlimit;
	private Float outlierLowerlimit;
	private Float outlierUpperlimit;
	private String alarmLevel;
	private Float goalvalue;
	private Float referencevalue;
	private String measurementtype;
	private String timeUnit;
	private String frequency;
	private LocalDateTime timeCreated;
	private LocalDateTime timeDeleted;
	private Set<OiBackgroundpropertyValue> oiBackgroundpropertyValues = new HashSet<OiBackgroundpropertyValue>(0);
	private Set<GroupMember> groupMembers = new HashSet<GroupMember>(0);
	private Set<OiMeasuredproperty> oiMeasuredproperties = new HashSet<OiMeasuredproperty>(0);

	public OitypeProperty() {
	}

	public OitypeProperty(int id) {
		this.id = id;
	}

	public OitypeProperty(int id, Codes codes, Oitype oitype, String oitypeTitle, String title, String reportTitle,
			String sourceTitle, String description, String dataSource, String variabletype, String propertytype,
			String datatype, String quanttype, String numunit, String codesTitle, Float lowerlimit, Float upperlimit,
			Float alarmLowerlimit, Float alarmUpperlimit, Float outlierLowerlimit, Float outlierUpperlimit,
			String alarmLevel, Float goalvalue, Float referencevalue, String measurementtype, String timeUnit,
			String frequency, LocalDateTime timeCreated, LocalDateTime timeDeleted,
			Set<OiBackgroundpropertyValue> oiBackgroundpropertyValues, Set<GroupMember> groupMembers,
			Set<OiMeasuredproperty> oiMeasuredproperties) {
		this.id = id;
		this.codes = codes;
		this.oitype = oitype;
		this.oitypeTitle = oitypeTitle;
		this.title = title;
		this.reportTitle = reportTitle;
		this.sourceTitle = sourceTitle;
		this.description = description;
		this.dataSource = dataSource;
		this.variabletype = variabletype;
		this.propertytype = propertytype;
		this.datatype = datatype;
		this.quanttype = quanttype;
		this.numunit = numunit;
		this.codesTitle = codesTitle;
		this.lowerlimit = lowerlimit;
		this.upperlimit = upperlimit;
		this.alarmLowerlimit = alarmLowerlimit;
		this.alarmUpperlimit = alarmUpperlimit;
		this.outlierLowerlimit = outlierLowerlimit;
		this.outlierUpperlimit = outlierUpperlimit;
		this.alarmLevel = alarmLevel;
		this.goalvalue = goalvalue;
		this.referencevalue = referencevalue;
		this.measurementtype = measurementtype;
		this.timeUnit = timeUnit;
		this.frequency = frequency;
		this.timeCreated = timeCreated;
		this.timeDeleted = timeDeleted;
		this.oiBackgroundpropertyValues = oiBackgroundpropertyValues;
		this.groupMembers = groupMembers;
		this.oiMeasuredproperties = oiMeasuredproperties;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codes_id")
	public Codes getCodes() {
		return this.codes;
	}

	public void setCodes(Codes codes) {
		this.codes = codes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "oitype_id")
	public Oitype getOitype() {
		return this.oitype;
	}

	public void setOitype(Oitype oitype) {
		this.oitype = oitype;
	}

	@Column(name = "oitype_title")
	public String getOitypeTitle() {
		return this.oitypeTitle;
	}

	public void setOitypeTitle(String oitypeTitle) {
		this.oitypeTitle = oitypeTitle;
	}

	@Column(name = "title")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "report_title")
	public String getReportTitle() {
		return this.reportTitle;
	}

	public void setReportTitle(String reportTitle) {
		this.reportTitle = reportTitle;
	}

	@Column(name = "source_title")
	public String getSourceTitle() {
		return this.sourceTitle;
	}

	public void setSourceTitle(String sourceTitle) {
		this.sourceTitle = sourceTitle;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "data_source")
	public String getDataSource() {
		return this.dataSource;
	}

	public void setDataSource(String dataSource) {
		this.dataSource = dataSource;
	}

	@Column(name = "variabletype")
	public String getVariabletype() {
		return this.variabletype;
	}

	public void setVariabletype(String variabletype) {
		this.variabletype = variabletype;
	}

	@Column(name = "propertytype")
	public String getPropertytype() {
		return this.propertytype;
	}

	public void setPropertytype(String propertytype) {
		this.propertytype = propertytype;
	}

	@Column(name = "datatype")
	public String getDatatype() {
		return this.datatype;
	}

	public void setDatatype(String datatype) {
		this.datatype = datatype;
	}

	@Column(name = "quanttype")
	public String getQuanttype() {
		return this.quanttype;
	}

	public void setQuanttype(String quanttype) {
		this.quanttype = quanttype;
	}

	@Column(name = "numunit")
	public String getNumunit() {
		return this.numunit;
	}

	public void setNumunit(String numunit) {
		this.numunit = numunit;
	}

	@Column(name = "codes_title")
	public String getCodesTitle() {
		return this.codesTitle;
	}

	public void setCodesTitle(String codesTitle) {
		this.codesTitle = codesTitle;
	}

	@Column(name = "lowerlimit", precision = 8, scale = 8)
	public Float getLowerlimit() {
		return this.lowerlimit;
	}

	public void setLowerlimit(Float lowerlimit) {
		this.lowerlimit = lowerlimit;
	}

	@Column(name = "upperlimit", precision = 8, scale = 8)
	public Float getUpperlimit() {
		return this.upperlimit;
	}

	public void setUpperlimit(Float upperlimit) {
		this.upperlimit = upperlimit;
	}

	@Column(name = "alarm_lowerlimit", precision = 8, scale = 8)
	public Float getAlarmLowerlimit() {
		return this.alarmLowerlimit;
	}

	public void setAlarmLowerlimit(Float alarmLowerlimit) {
		this.alarmLowerlimit = alarmLowerlimit;
	}

	@Column(name = "alarm_upperlimit", precision = 8, scale = 8)
	public Float getAlarmUpperlimit() {
		return this.alarmUpperlimit;
	}

	public void setAlarmUpperlimit(Float alarmUpperlimit) {
		this.alarmUpperlimit = alarmUpperlimit;
	}

	@Column(name = "outlier_lowerlimit", precision = 8, scale = 8)
	public Float getOutlierLowerlimit() {
		return this.outlierLowerlimit;
	}

	public void setOutlierLowerlimit(Float outlierLowerlimit) {
		this.outlierLowerlimit = outlierLowerlimit;
	}

	@Column(name = "outlier_upperlimit", precision = 8, scale = 8)
	public Float getOutlierUpperlimit() {
		return this.outlierUpperlimit;
	}

	public void setOutlierUpperlimit(Float outlierUpperlimit) {
		this.outlierUpperlimit = outlierUpperlimit;
	}

	@Column(name = "alarm_level")
	public String getAlarmLevel() {
		return this.alarmLevel;
	}

	public void setAlarmLevel(String alarmLevel) {
		this.alarmLevel = alarmLevel;
	}

	@Column(name = "goalvalue", precision = 8, scale = 8)
	public Float getGoalvalue() {
		return this.goalvalue;
	}

	public void setGoalvalue(Float goalvalue) {
		this.goalvalue = goalvalue;
	}

	@Column(name = "referencevalue", precision = 8, scale = 8)
	public Float getReferencevalue() {
		return this.referencevalue;
	}

	public void setReferencevalue(Float referencevalue) {
		this.referencevalue = referencevalue;
	}

	@Column(name = "measurementtype")
	public String getMeasurementtype() {
		return this.measurementtype;
	}

	public void setMeasurementtype(String measurementtype) {
		this.measurementtype = measurementtype;
	}

	@Column(name = "time_unit")
	public String getTimeUnit() {
		return this.timeUnit;
	}

	public void setTimeUnit(String timeUnit) {
		this.timeUnit = timeUnit;
	}

	@Column(name = "frequency")
	public String getFrequency() {
		return this.frequency;
	}

	public void setFrequency(String frequency) {
		this.frequency = frequency;
	}

	@Column(name = "time_created", length = 29)
	public LocalDateTime getTimeCreated() {
		return this.timeCreated;
	}

	public void setTimeCreated(LocalDateTime timeCreated) {
		this.timeCreated = timeCreated;
	}

	@Column(name = "time_deleted", length = 29)
	public LocalDateTime getTimeDeleted() {
		return this.timeDeleted;
	}

	public void setTimeDeleted(LocalDateTime timeDeleted) {
		this.timeDeleted = timeDeleted;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "oitypeProperty")
	public Set<OiBackgroundpropertyValue> getOiBackgroundpropertyValues() {
		return this.oiBackgroundpropertyValues;
	}

	public void setOiBackgroundpropertyValues(Set<OiBackgroundpropertyValue> oiBackgroundpropertyValues) {
		this.oiBackgroundpropertyValues = oiBackgroundpropertyValues;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "oitypeProperty")
	public Set<GroupMember> getGroupMembers() {
		return this.groupMembers;
	}

	public void setGroupMembers(Set<GroupMember> groupMembers) {
		this.groupMembers = groupMembers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "oitypeProperty")
	public Set<OiMeasuredproperty> getOiMeasuredproperties() {
		return this.oiMeasuredproperties;
	}

	public void setOiMeasuredproperties(Set<OiMeasuredproperty> oiMeasuredproperties) {
		this.oiMeasuredproperties = oiMeasuredproperties;
	}

}
