package fi.vtt.openva.domain;
//OpenVA - Open software platform for visual analytics
//
//Copyright (c) 2018, VTT Technical Research Centre of Finland Ltd
//All rights reserved.
//Redistribution and use in source and binary forms, with or without
//modification, are permitted provided that the following conditions are met:
//
// 1) Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2) Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3) Neither the name of the VTT Technical Research Centre of Finland nor the
//    names of its contributors may be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
//THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS ``AS IS'' AND ANY
//EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
//WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
//DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS AND CONTRIBUTORS BE LIABLE FOR ANY
//DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
//(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StoredSelections generated by hbm2java
 */
@Entity
@Table(name = "stored_selections", schema = "public")
public class StoredSelections implements java.io.Serializable {

	private int id;
	private String title;
	private String description;
	private LocalDateTime timeCreated;
	private LocalDateTime lastModified;
	private LocalDateTime timeDeleted;
	private Set<StoredObjectofinterest> storedObjectofinterests = new HashSet<StoredObjectofinterest>(0);
	private Set<StoredOitypeProperty> storedOitypeProperties = new HashSet<StoredOitypeProperty>(0);
	private Set<StoredFilter> storedFilters = new HashSet<StoredFilter>(0);

	public StoredSelections() {
	}

	public StoredSelections(int id) {
		this.id = id;
	}

	public StoredSelections(int id, String title, String description, LocalDateTime timeCreated,
			LocalDateTime lastModified, LocalDateTime timeDeleted, Set<StoredObjectofinterest> storedObjectofinterests,
			Set<StoredOitypeProperty> storedOitypeProperties, Set<StoredFilter> storedFilters) {
		this.id = id;
		this.title = title;
		this.description = description;
		this.timeCreated = timeCreated;
		this.lastModified = lastModified;
		this.timeDeleted = timeDeleted;
		this.storedObjectofinterests = storedObjectofinterests;
		this.storedOitypeProperties = storedOitypeProperties;
		this.storedFilters = storedFilters;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "title")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "time_created", length = 29)
	public LocalDateTime getTimeCreated() {
		return this.timeCreated;
	}

	public void setTimeCreated(LocalDateTime timeCreated) {
		this.timeCreated = timeCreated;
	}

	@Column(name = "last_modified", length = 29)
	public LocalDateTime getLastModified() {
		return this.lastModified;
	}

	public void setLastModified(LocalDateTime lastModified) {
		this.lastModified = lastModified;
	}

	@Column(name = "time_deleted", length = 29)
	public LocalDateTime getTimeDeleted() {
		return this.timeDeleted;
	}

	public void setTimeDeleted(LocalDateTime timeDeleted) {
		this.timeDeleted = timeDeleted;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "storedSelections")
	public Set<StoredObjectofinterest> getStoredObjectofinterests() {
		return this.storedObjectofinterests;
	}

	public void setStoredObjectofinterests(Set<StoredObjectofinterest> storedObjectofinterests) {
		this.storedObjectofinterests = storedObjectofinterests;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "storedSelections")
	public Set<StoredOitypeProperty> getStoredOitypeProperties() {
		return this.storedOitypeProperties;
	}

	public void setStoredOitypeProperties(Set<StoredOitypeProperty> storedOitypeProperties) {
		this.storedOitypeProperties = storedOitypeProperties;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "storedSelections")
	public Set<StoredFilter> getStoredFilters() {
		return this.storedFilters;
	}

	public void setStoredFilters(Set<StoredFilter> storedFilters) {
		this.storedFilters = storedFilters;
	}

}
