package fi.vtt.openva.domain;
//OpenVA - Open software platform for visual analytics
//
//Copyright (c) 2018, VTT Technical Research Centre of Finland Ltd
//All rights reserved.
//Redistribution and use in source and binary forms, with or without
//modification, are permitted provided that the following conditions are met:
//
// 1) Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2) Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3) Neither the name of the VTT Technical Research Centre of Finland nor the
//    names of its contributors may be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
//THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS ``AS IS'' AND ANY
//EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
//WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
//DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS AND CONTRIBUTORS BE LIABLE FOR ANY
//DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
//(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

import java.time.LocalDateTime;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * StoredObjectofinterest generated by hbm2java
 */
@Entity
@Table(name = "stored_objectofinterest", schema = "public")
public class StoredObjectofinterest implements java.io.Serializable {

	private int id;
	private Objectofinterest objectofinterest;
	private StoredSelections storedSelections;
	private String oiTitle;
	private String storedSelectionsTitle;
	private LocalDateTime timeCreated;
	private LocalDateTime lastModified;
	private LocalDateTime timeDeleted;

	public StoredObjectofinterest() {
	}

	public StoredObjectofinterest(int id) {
		this.id = id;
	}

	public StoredObjectofinterest(int id, Objectofinterest objectofinterest, StoredSelections storedSelections,
			String oiTitle, String storedSelectionsTitle, LocalDateTime timeCreated, LocalDateTime lastModified,
			LocalDateTime timeDeleted) {
		this.id = id;
		this.objectofinterest = objectofinterest;
		this.storedSelections = storedSelections;
		this.oiTitle = oiTitle;
		this.storedSelectionsTitle = storedSelectionsTitle;
		this.timeCreated = timeCreated;
		this.lastModified = lastModified;
		this.timeDeleted = timeDeleted;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(cascade = CascadeType.ALL)
	@JoinColumn(name = "oi_id")
	public Objectofinterest getObjectofinterest() {
		return this.objectofinterest;
	}

	public void setObjectofinterest(Objectofinterest objectofinterest) {
		this.objectofinterest = objectofinterest;
	}

	@ManyToOne(cascade = CascadeType.ALL)
	@JoinColumn(name = "stored_selections_id")
	public StoredSelections getStoredSelections() {
		return this.storedSelections;
	}

	public void setStoredSelections(StoredSelections storedSelections) {
		this.storedSelections = storedSelections;
	}

	@Column(name = "oi_title")
	public String getOiTitle() {
		return this.oiTitle;
	}

	public void setOiTitle(String oiTitle) {
		this.oiTitle = oiTitle;
	}

	@Column(name = "stored_selections_title")
	public String getStoredSelectionsTitle() {
		return this.storedSelectionsTitle;
	}

	public void setStoredSelectionsTitle(String storedSelectionsTitle) {
		this.storedSelectionsTitle = storedSelectionsTitle;
	}

	@Column(name = "time_created", length = 29)
	public LocalDateTime getTimeCreated() {
		return this.timeCreated;
	}

	public void setTimeCreated(LocalDateTime timeCreated) {
		this.timeCreated = timeCreated;
	}

	@Column(name = "last_modified", length = 29)
	public LocalDateTime getLastModified() {
		return this.lastModified;
	}

	public void setLastModified(LocalDateTime lastModified) {
		this.lastModified = lastModified;
	}

	@Column(name = "time_deleted", length = 29)
	public LocalDateTime getTimeDeleted() {
		return this.timeDeleted;
	}

	public void setTimeDeleted(LocalDateTime timeDeleted) {
		this.timeDeleted = timeDeleted;
	}

}
