package fi.vtt.openva.domain;
// Generated Feb 25, 2019 2:11:47 PM by Hibernate Tools 5.2.11.Final

import java.time.LocalDateTime;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * StoredFilter generated by hbm2java
 */
@Entity
@Table(name = "stored_filter", schema = "public")
public class StoredFilter implements java.io.Serializable {

	private int id;
	private StoredSelections storedSelections;
	private String filter;
	private String storedSelectionsTitle;
	private LocalDateTime timeCreated;
	private LocalDateTime lastModified;
	private LocalDateTime timeDeleted;
	private String key;
	private String value;
	private String label;

	public StoredFilter() {
	}

	public StoredFilter(int id) {
		this.id = id;
	}

	public StoredFilter(int id, StoredSelections storedSelections, String filter, String storedSelectionsTitle,
			LocalDateTime timeCreated, LocalDateTime lastModified, LocalDateTime timeDeleted, String key, String value,
			String label) {
		this.id = id;
		this.storedSelections = storedSelections;
		this.filter = filter;
		this.storedSelectionsTitle = storedSelectionsTitle;
		this.timeCreated = timeCreated;
		this.lastModified = lastModified;
		this.timeDeleted = timeDeleted;
		this.key = key;
		this.value = value;
		this.label = label;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(cascade = CascadeType.ALL)
	@JoinColumn(name = "stored_selections_id")
	public StoredSelections getStoredSelections() {
		return this.storedSelections;
	}

	public void setStoredSelections(StoredSelections storedSelections) {
		this.storedSelections = storedSelections;
	}

	@Column(name = "filter")
	public String getFilter() {
		return this.filter;
	}

	public void setFilter(String filter) {
		this.filter = filter;
	}

	@Column(name = "stored_selections_title")
	public String getStoredSelectionsTitle() {
		return this.storedSelectionsTitle;
	}

	public void setStoredSelectionsTitle(String storedSelectionsTitle) {
		this.storedSelectionsTitle = storedSelectionsTitle;
	}

	@Column(name = "time_created", length = 29)
	public LocalDateTime getTimeCreated() {
		return this.timeCreated;
	}

	public void setTimeCreated(LocalDateTime timeCreated) {
		this.timeCreated = timeCreated;
	}

	@Column(name = "last_modified", length = 29)
	public LocalDateTime getLastModified() {
		return this.lastModified;
	}

	public void setLastModified(LocalDateTime lastModified) {
		this.lastModified = lastModified;
	}

	@Column(name = "time_deleted", length = 29)
	public LocalDateTime getTimeDeleted() {
		return this.timeDeleted;
	}

	public void setTimeDeleted(LocalDateTime timeDeleted) {
		this.timeDeleted = timeDeleted;
	}

	@Column(name = "key")
	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	@Column(name = "value")
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "label")
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

}
