package fi.vtt.openva.domain;
//OpenVA - Open software platform for visual analytics
//
//Copyright (c) 2018, VTT Technical Research Centre of Finland Ltd
//All rights reserved.
//Redistribution and use in source and binary forms, with or without
//modification, are permitted provided that the following conditions are met:
//
// 1) Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2) Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3) Neither the name of the VTT Technical Research Centre of Finland nor the
//    names of its contributors may be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
//THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS ``AS IS'' AND ANY
//EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
//WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
//DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS AND CONTRIBUTORS BE LIABLE FOR ANY
//DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
//(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
//LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
//(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

import java.time.LocalDateTime;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Visualization generated by hbm2java
 */
@Entity
@Table(name = "visualization", schema = "public")
public class Visualization implements java.io.Serializable {

	private int id;
	private String method;
	private String title;
	private String oitypetitle;
	private String oitypecount;
	private Integer oismin;
	private Integer oismax;
	private Integer propertymin;
	private Integer propertymax;
	private String datatype;
	private String propertytype;
	private String engine;
	private LocalDateTime timeCreated;
	private LocalDateTime timeDeleted;
	private String applicationTitle;
	private String formats;
	private String oitypeProperty;
	private String oitypePropertyValue;
	private String quanttype;

	public Visualization() {
	}

	public Visualization(int id) {
		this.id = id;
	}

	public Visualization(int id, String method, String title, String oitypetitle, String oitypecount, Integer oismin,
			Integer oismax, Integer propertymin, Integer propertymax, String datatype, String propertytype,
			String engine, LocalDateTime timeCreated, LocalDateTime timeDeleted, String applicationTitle,
			String formats, String oitypeProperty, String oitypePropertyValue, String quanttype) {
		this.id = id;
		this.method = method;
		this.title = title;
		this.oitypetitle = oitypetitle;
		this.oitypecount = oitypecount;
		this.oismin = oismin;
		this.oismax = oismax;
		this.propertymin = propertymin;
		this.propertymax = propertymax;
		this.datatype = datatype;
		this.propertytype = propertytype;
		this.engine = engine;
		this.timeCreated = timeCreated;
		this.timeDeleted = timeDeleted;
		this.applicationTitle = applicationTitle;
		this.formats = formats;
		this.oitypeProperty = oitypeProperty;
		this.oitypePropertyValue = oitypePropertyValue;
		this.quanttype = quanttype;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "method")
	public String getMethod() {
		return this.method;
	}

	public void setMethod(String method) {
		this.method = method;
	}

	@Column(name = "title")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "oitypetitle")
	public String getOitypetitle() {
		return this.oitypetitle;
	}

	public void setOitypetitle(String oitypetitle) {
		this.oitypetitle = oitypetitle;
	}

	@Column(name = "oitypecount")
	public String getOitypecount() {
		return this.oitypecount;
	}

	public void setOitypecount(String oitypecount) {
		this.oitypecount = oitypecount;
	}

	@Column(name = "oismin")
	public Integer getOismin() {
		return this.oismin;
	}

	public void setOismin(Integer oismin) {
		this.oismin = oismin;
	}

	@Column(name = "oismax")
	public Integer getOismax() {
		return this.oismax;
	}

	public void setOismax(Integer oismax) {
		this.oismax = oismax;
	}

	@Column(name = "propertymin")
	public Integer getPropertymin() {
		return this.propertymin;
	}

	public void setPropertymin(Integer propertymin) {
		this.propertymin = propertymin;
	}

	@Column(name = "propertymax")
	public Integer getPropertymax() {
		return this.propertymax;
	}

	public void setPropertymax(Integer propertymax) {
		this.propertymax = propertymax;
	}

	@Column(name = "datatype")
	public String getDatatype() {
		return this.datatype;
	}

	public void setDatatype(String datatype) {
		this.datatype = datatype;
	}

	@Column(name = "propertytype")
	public String getPropertytype() {
		return this.propertytype;
	}

	public void setPropertytype(String propertytype) {
		this.propertytype = propertytype;
	}

	@Column(name = "engine")
	public String getEngine() {
		return this.engine;
	}

	public void setEngine(String engine) {
		this.engine = engine;
	}

	@Column(name = "time_created", length = 29)
	public LocalDateTime getTimeCreated() {
		return this.timeCreated;
	}

	public void setTimeCreated(LocalDateTime timeCreated) {
		this.timeCreated = timeCreated;
	}

	@Column(name = "time_deleted", length = 29)
	public LocalDateTime getTimeDeleted() {
		return this.timeDeleted;
	}

	public void setTimeDeleted(LocalDateTime timeDeleted) {
		this.timeDeleted = timeDeleted;
	}

	@Column(name = "application_title")
	public String getApplicationTitle() {
		return this.applicationTitle;
	}

	public void setApplicationTitle(String applicationTitle) {
		this.applicationTitle = applicationTitle;
	}

	@Column(name = "formats")
	public String getFormats() {
		return this.formats;
	}

	public void setFormats(String formats) {
		this.formats = formats;
	}

	@Column(name = "oitype_property")
	public String getOitypeProperty() {
		return this.oitypeProperty;
	}

	public void setOitypeProperty(String oitypeProperty) {
		this.oitypeProperty = oitypeProperty;
	}

	@Column(name = "oitype_property_value")
	public String getOitypePropertyValue() {
		return this.oitypePropertyValue;
	}

	public void setOitypePropertyValue(String oitypePropertyValue) {
		this.oitypePropertyValue = oitypePropertyValue;
	}

	@Column(name = "quanttype")
	public String getQuanttype() {
		return this.quanttype;
	}

	public void setQuanttype(String quanttype) {
		this.quanttype = quanttype;
	}

}
