// default package
// Generated Aug 29, 2018 12:00:35 PM by Hibernate Tools 5.2.0.Beta1

package fi.vtt.openva.domain;

import java.time.LocalDateTime;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Visualization generated by hbm2java
 */
@Entity
@Table(name = "visualization", schema = "public")
public class Visualization implements java.io.Serializable {

	private int id;
	private String method;
	private String title;
	private String oitypetitle;
	private String oistype;
	private Integer oismin;
	private Integer oismax;
	private Integer propertymin;
	private Integer propertymax;
	private String datatype;
	private String variabletype;
	private String engine;
	private LocalDateTime timeCreated;
	private LocalDateTime timeDeleted;
	private String applicationTitle;

	public Visualization() {
	}

	public Visualization(int id) {
		this.id = id;
	}

	public Visualization(int id, String method, String title, String oitypetitle, String oistype, Integer oismin,
			Integer oismax, Integer propertymin, Integer propertymax, String datatype, String variabletype,
			String engine, LocalDateTime timeCreated, LocalDateTime timeDeleted, String application,
			String applicationTitle) {
		this.id = id;
		this.method = method;
		this.title = title;
		this.oitypetitle = oitypetitle;
		this.oistype = oistype;
		this.oismin = oismin;
		this.oismax = oismax;
		this.propertymin = propertymin;
		this.propertymax = propertymax;
		this.datatype = datatype;
		this.variabletype = variabletype;
		this.engine = engine;
		this.timeCreated = timeCreated;
		this.timeDeleted = timeDeleted;
		this.applicationTitle = applicationTitle;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "method")
	public String getMethod() {
		return this.method;
	}

	public void setMethod(String method) {
		this.method = method;
	}

	@Column(name = "title")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "oitypetitle")
	public String getOitypetitle() {
		return this.oitypetitle;
	}

	public void setOitypetitle(String oitypetitle) {
		this.oitypetitle = oitypetitle;
	}

	@Column(name = "oistype")
	public String getOistype() {
		return this.oistype;
	}

	public void setOistype(String oistype) {
		this.oistype = oistype;
	}

	@Column(name = "oismin")
	public Integer getOismin() {
		return this.oismin;
	}

	public void setOismin(Integer oismin) {
		this.oismin = oismin;
	}

	@Column(name = "oismax")
	public Integer getOismax() {
		return this.oismax;
	}

	public void setOismax(Integer oismax) {
		this.oismax = oismax;
	}

	@Column(name = "propertymin")
	public Integer getPropertymin() {
		return this.propertymin;
	}

	public void setPropertymin(Integer propertymin) {
		this.propertymin = propertymin;
	}

	@Column(name = "propertymax")
	public Integer getPropertymax() {
		return this.propertymax;
	}

	public void setPropertymax(Integer propertymax) {
		this.propertymax = propertymax;
	}

	@Column(name = "datatype")
	public String getDatatype() {
		return this.datatype;
	}

	public void setDatatype(String datatype) {
		this.datatype = datatype;
	}

	@Column(name = "variabletype")
	public String getVariabletype() {
		return this.variabletype;
	}

	public void setVariabletype(String variabletype) {
		this.variabletype = variabletype;
	}

	@Column(name = "engine")
	public String getEngine() {
		return this.engine;
	}

	public void setEngine(String engine) {
		this.engine = engine;
	}

	@Column(name = "time_created", length = 29)
	public LocalDateTime getTimeCreated() {
		return this.timeCreated;
	}

	public void setTimeCreated(LocalDateTime timeCreated) {
		this.timeCreated = timeCreated;
	}

	@Column(name = "time_deleted", length = 29)
	public LocalDateTime getTimeDeleted() {
		return this.timeDeleted;
	}

	public void setTimeDeleted(LocalDateTime timeDeleted) {
		this.timeDeleted = timeDeleted;
	}


	@Column(name = "application_title")
	public String getApplicationTitle() {
		return this.applicationTitle;
	}

	public void setApplicationTitle(String applicationTitle) {
		this.applicationTitle = applicationTitle;
	}

}
